name: 💡 Предложение функции
description: Предложить новую функцию или улучшение
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение! Ваши идеи помогают улучшить проект. Пожалуйста, заполните форму ниже.

  - type: checkboxes
    id: checks
    attributes:
      label: Предварительные проверки
      description: Перед созданием предложения убедитесь, что вы выполнили следующие проверки
      options:
        - label: Я проверил существующие [Issues](https://github.com/stp008/litellm-gigachat/issues) и [Pull Requests](https://github.com/stp008/litellm-gigachat/pulls)
          required: true
        - label: Эта функция еще не реализована в проекте
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Краткое описание
      description: Кратко опишите предлагаемую функцию
      placeholder: "Например: Добавить поддержку новой модели GigaChat-Ultra"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Мотивация и проблема
      description: Какую проблему решает эта функция? Почему она нужна?
      placeholder: |
        Опишите:
        - Какую проблему вы пытаетесь решить?
        - Как эта функция улучшит проект?
        - Кому это будет полезно?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
      description: Подробно опишите, как должна работать функция
      placeholder: |
        Опишите:
        - Как должна работать функция?
        - Какой интерфейс предполагается?
        - Примеры использования
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Примеры использования
      description: Покажите, как будет использоваться новая функция
      render: python
      placeholder: |
        # Пример кода, показывающий использование новой функции
        client = openai.OpenAI(base_url="http://localhost:4000")
        
        response = client.chat.completions.create(
            model="gigachat-ultra",  # новая модель
            messages=[{"role": "user", "content": "Привет!"}]
        )

  - type: dropdown
    id: category
    attributes:
      label: Категория функции
      description: К какой категории относится предложение?
      options:
        - "🤖 Новые модели AI"
        - "🔌 Интеграции с инструментами"
        - "⚡ Производительность"
        - "🔐 Безопасность"
        - "📊 Мониторинг и аналитика"
        - "🛠️ Developer Experience"
        - "📖 Документация"
        - "🧪 Тестирование"
        - "🎨 UI/UX"
        - "🔧 Конфигурация"
        - "📦 Развертывание"
        - "🌐 API расширения"
        - "Другое"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Предполагаемая сложность
      description: Насколько сложной кажется реализация?
      options:
        - "🟢 Простая - несколько часов работы"
        - "🟡 Средняя - несколько дней работы"
        - "🟠 Сложная - несколько недель работы"
        - "🔴 Очень сложная - требует архитектурных изменений"
        - "❓ Не уверен"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Возможная реализация
      description: Если у вас есть идеи по реализации, поделитесь ими
      placeholder: |
        - Какие файлы нужно изменить?
        - Какие новые компоненты создать?
        - Какие зависимости добавить?
        - Архитектурные соображения

  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативные решения
      description: Рассматривали ли вы другие способы решения проблемы?
      placeholder: |
        - Какие альтернативы вы рассматривали?
        - Почему предложенное решение лучше?
        - Есть ли обходные пути?

  - type: checkboxes
    id: impact
    attributes:
      label: Влияние на проект
      description: Как эта функция повлияет на проект? (выберите все подходящие)
      options:
        - label: 🔄 Требует изменения существующего API
        - label: 📦 Требует новые зависимости
        - label: 🏗️ Требует архитектурные изменения
        - label: 📖 Требует обновление документации
        - label: 🧪 Требует новые тесты
        - label: ⚡ Может повлиять на производительность
        - label: 🔐 Может повлиять на безопасность
        - label: 🔧 Требует изменения конфигурации

  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      description: Насколько важна эта функция для вас?
      options:
        - "🔴 Критический - блокирует работу"
        - "🟠 Высокий - значительно улучшит работу"
        - "🟡 Средний - было бы полезно"
        - "🟢 Низкий - nice to have"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Готовность к участию
      description: Готовы ли вы помочь с реализацией?
      options:
        - label: 💻 Я готов реализовать эту функцию самостоятельно
        - label: 🤝 Я готов помочь с реализацией
        - label: 🧪 Я готов помочь с тестированием
        - label: 📖 Я готов помочь с документацией
        - label: 💡 Я могу только предложить идею

  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: Любая дополнительная информация, ссылки, скриншоты и т.д.
      placeholder: |
        - Ссылки на похожие реализации
        - Скриншоты или диаграммы
        - Связанные issues или PR
        - Дополнительные соображения

  - type: checkboxes
    id: target_users
    attributes:
      label: Целевая аудитория
      description: Кому будет полезна эта функция? (выберите все подходящие)
      options:
        - label: 👨‍💻 Разработчики Python
        - label: 🤖 Пользователи AI-ассистентов (Cline, Cursor и т.д.)
        - label: 🏢 Корпоративные пользователи
        - label: 🎓 Исследователи и студенты
        - label: 🚀 DevOps инженеры
        - label: 📊 Data Scientists
        - label: 🌐 Веб-разработчики
        - label: 📱 Мобильные разработчики
